export interface ObservationPrice { provider: string; model: string; input_micros_per_million: number; output_micros_per_million: number; note?: string }
export interface ObservationPolicy { currency: string; project_budget_micros: number; task_budget_micros: number; project_max_calls: number; task_max_calls: number; max_output_tokens: number; max_input_estimate: number; require_known_price: boolean; block_unknown_cost: boolean; failure_threshold: number; cooldown_seconds: number; paused_providers: string[]; prices: ObservationPrice[] }
export interface ObservationTotals { calls: number; completed: number; failed: number; pending: number; unknown_cost: number; unknown_usage: number; input_tokens: number; output_tokens: number; known_cost_micros: number; reserved_micros: number }
export interface ObservationAttempt { id: string; logical_id: string; request_hash: string; task_id: string; transaction_id: string; chapter: number; agent: string; operation: string; provider: string; model: string; state: string; started_at: string; ended_at: string | null; input_tokens: number | null; output_tokens: number | null; usage_source: string; input_estimate: number; output_limit: number; currency: string; price_revision: number; price: ObservationPrice | null; cost_micros: number | null; reserved_micros: number; cost_source: string; error_code?: string; boundary: string }
export interface ObservationHealth { provider: string; state: string; last_error: string; last_attempt_at: string; consecutive_failures: number; cooldown_until: string | null; manually_paused: boolean }
export interface ObservationPage { settings: { revision: number; policy: ObservationPolicy }; totals: ObservationTotals; groups: { agent: string; provider: string; model: string; totals: ObservationTotals }[]; attempts: ObservationAttempt[]; health: ObservationHealth[]; replays: number; legacy_untracked_calls: number; limit: number; offset: number; total: number; filter_task: string; filter_chapter: number }
export interface ObservationMutation { expected_revision: number; policy?: ObservationPolicy; reconcile?: { attempt_id: string; cost_micros: number; confirm: boolean } }
export interface ObservationChange { revision: number; policy?: ObservationPolicy; before?: ObservationAttempt; after?: ObservationAttempt }
export interface ObservationFinding { code: string; severity: string; count: number; chapter?: number; task_id?: string; message: string; action: string }
export interface ObservationDiagnostics { findings: ObservationFinding[]; generated_at: string; task_history_limit: number }
