import { render, screen, fireEvent, waitFor, cleanup } from '@testing-library/svelte';
import { afterEach, expect, it, vi } from 'vitest';
import Observability from './Observability.svelte';
const policy={currency:'USD',project_budget_micros:0,task_budget_micros:0,project_max_calls:0,task_max_calls:0,max_output_tokens:8192,max_input_estimate:100000,require_known_price:false,block_unknown_cost:false,failure_threshold:3,cooldown_seconds:60,paused_providers:[],prices:[]};
const totals={calls:1,completed:1,failed:0,pending:0,unknown_cost:1,unknown_usage:1,input_tokens:0,output_tokens:0,known_cost_micros:0,reserved_micros:0};
function fixture(){return {settings:{revision:1,policy},totals,groups:[],health:[],attempts:[{id:'a',logical_id:'logical',task_id:'manual',chapter:1,agent:'writer',operation:'draft',provider:'local',model:'test',state:'completed',started_at:'2026-09-06T00:00:00Z',ended_at:null,input_tokens:null,output_tokens:null,cost_micros:null,cost_source:'unknown',currency:'USD'}],replays:2,legacy_untracked_calls:3,limit:50,offset:0,total:1};}
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it('keeps unknown usage and costs explicit and does not call models on load',async()=>{const calls:string[]=[];vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{const u=String(input);calls.push(u);return new Response(JSON.stringify(u.includes('/diagnostics')?{findings:[]}:u.includes('/observability')?fixture():{projects:[{id:'p',title:'Book'}]}),{status:200});}));render(Observability);await screen.findByText('未知 → 未知');expect(screen.getByText('未知')).toBeTruthy();expect(calls.every(u=>!u.includes('/generate')&&!u.includes('/resume'))).toBe(true);});
it('requires explicit invoice confirmation and sends a revision and idempotency key',async()=>{const writes:RequestInit[]=[];vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{if(init?.method==='POST'){writes.push(init);return new Response(JSON.stringify({revision:2}),{status:200});}const u=String(input);return new Response(JSON.stringify(u.includes('/diagnostics')?{findings:[]}:u.includes('/observability')?fixture():{projects:[{id:'p',title:'Book'}]}),{status:200});}));render(Observability);await fireEvent.click(await screen.findByText('核对费用'));const button=screen.getByRole('button',{name:'记录人工对账'}) as HTMLButtonElement;expect(button.disabled).toBe(true);await fireEvent.click(screen.getByLabelText('已核对服务商记录，确认该金额'));await fireEvent.click(button);await waitFor(()=>expect(writes).toHaveLength(1));const payload=JSON.parse(String(writes[0].body));expect(payload.expected_revision).toBe(1);expect(payload.reconcile.confirm).toBe(true);expect((writes[0].headers as Record<string,string>)['Idempotency-Key']).toBeTruthy();});
