<script lang="ts">
  import { t, text, findingText, codeText, label as stateLabel, message as uiMessage, errorMessage } from '../lib/i18n';
 import { onMount } from 'svelte';
 import { api } from '../lib/api';
 import { recentEvents } from '../lib/events';
 import type { ProjectSummary } from '../lib/types';
 import type { ObservationPage, ObservationPolicy, ObservationFinding } from '../lib/observability';
 let projects: ProjectSummary[] = [], id = '', page: ObservationPage | null = null, findings: ObservationFinding[] = [];
 let error = '', notice = '', busy = false, loading = false, offset = 0, chapter = 0, task = '';
 let draft: ObservationPolicy | null = null, draftRevision = 0, projectBudget = 0, taskBudget = 0, paused = '';
 let reconciliation = '', amount = 0, confirmed = false; let sequence=0;
 const money = (n: number | null, currency = 'USD') => n === null ? uiMessage("ui_4d8c1c5b4283") : `${currency} ${(n / 1e6).toFixed(6)}`;
 function resetPolicy() { if (!page) return; draft = structuredClone(page.settings.policy); draftRevision = page.settings.revision; projectBudget=draft.project_budget_micros/1e6;taskBudget=draft.task_budget_micros/1e6;paused=draft.paused_providers.join(', '); }
 async function load(reset = false) {
  if (!id) return; const target=id, generation=++sequence; loading=true; error='';
  try { const [p,d]=await Promise.all([api.observations(target,task,chapter,offset),api.observationDiagnostics(target)]); if (id!==target || generation!==sequence) return; page=p;findings=d.findings;if (reset || !draft) resetPolicy(); }
  catch(e){if(id===target) error=errorMessage(e);} finally{if(generation===sequence)loading=false;}
 }
 async function choose() { page=null;draft=null;offset=0;task='';chapter=0;reconciliation='';confirmed=false;await load(true); }
 async function save() { if(!id||!draft)return;busy=true;error='';notice='';try{const p=structuredClone(draft);p.project_budget_micros=Math.round(projectBudget*1e6);p.task_budget_micros=Math.round(taskBudget*1e6);p.paused_providers=paused.split(',').map(v=>v.trim()).filter(Boolean);await api.saveObservations(id,{expected_revision:draftRevision,policy:p});notice=uiMessage("ui_64a42195f7f2");await load(true);}catch(e){error=errorMessage(e);}finally{busy=false;} }
 async function reconcile() {if(!page||!reconciliation||!confirmed)return;busy=true;error='';try{await api.saveObservations(id,{expected_revision:page.settings.revision,reconcile:{attempt_id:reconciliation,cost_micros:Math.round(amount*1e6),confirm:true}});reconciliation='';confirmed=false;await load(true);notice=uiMessage("ui_7ac5e7357d4c");}catch(e){error=errorMessage(e);}finally{busy=false;} }
 async function downloadReport(){try{const data=await api.observationReport(id);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='novelforge-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){error=errorMessage(e);}}
 onMount(()=>{let alive=true;let last=0;api.listProjects().then(p=>{if(!alive)return;projects=p.projects;id=new URLSearchParams(location.hash.split('?')[1]??'').get('project')??projects[0]?.id??'';void load(true);}).catch(e=>error=errorMessage(e));const stop=recentEvents.subscribe(events=>{const e=events[0];if(e&&typeof e.id==='number'&&e.id!==last&&e.project===id&&e.type==='observability.changed'){last=e.id;void load();}});const timer=setInterval(()=>void load(),10000);return()=>{alive=false;stop();clearInterval(timer);};});
</script>

<section class="space-y-6">
 <div><p class="text-xs uppercase tracking-widest text-primary">{$t("ui_eb2a269325bf")}</p><h1 class="text-2xl font-bold">{$t("ui_db87958c5298")}</h1><p class="mt-2 text-sm opacity-70">{$t("ui_24b93734b43d")}</p></div>
 <div class="flex flex-wrap gap-3"><label class="form-control flex-1"><span class="label-text">{$t("ui_d2668157d668")}</span><select class="select select-bordered" bind:value={id} on:change={choose} disabled={busy}>{#each projects as p}<option value={p.id}>{p.title}</option>{/each}</select></label><button class="btn" disabled={!id||busy||loading} on:click={()=>load()}>{$t("ui_aee887434131")}</button><button class="btn btn-outline" disabled={!id} on:click={downloadReport}>{$t("ui_29767de15a03")}</button></div>
 {#if error}<div role="alert" class="alert alert-error"><span>{$text(error)}</span></div>{/if}
 {#if notice}<div role="status" class="alert alert-success">{$text(notice)}</div>{/if}
 {#if page}
 <div class="grid gap-3 md:grid-cols-4">
  <div class="rounded-xl border border-base-300 p-4"><p class="text-sm opacity-60">{$t("ui_e9487e84c0ac")}</p><strong>{$text(money(page.totals.known_cost_micros,page.settings.policy.currency))}</strong><p class="text-xs">{$t("ui_422e904f4967", {p0: page.totals.unknown_cost, p1: page.totals.pending})}</p></div>
  <div class="rounded-xl border border-base-300 p-4"><p class="text-sm opacity-60">{$t("ui_a33efd1e384e")}</p><strong>{page.totals.calls}</strong><p class="text-xs">{$t("ui_a9aa017e680d", {p0: page.totals.completed, p1: page.totals.failed})}</p></div>
  <div class="rounded-xl border border-base-300 p-4"><p class="text-sm opacity-60">{$t("ui_488de5d139e8")}</p><strong>{page.totals.input_tokens} → {page.totals.output_tokens}</strong><p class="text-xs">{$t("ui_66d9bb378912", {p0: page.totals.unknown_usage})}</p></div>
  <div class="rounded-xl border border-base-300 p-4"><p class="text-sm opacity-60">{$t("ui_cb9825ea8c11")}</p><strong>{page.replays}</strong><p class="text-xs">{$t("ui_f0691d0463d1", {p0: page.legacy_untracked_calls})}</p></div>
 </div>
 <div class="rounded-xl border border-base-300 p-4"><h2 class="text-lg font-semibold">{$t("ui_56897d5961b4")}</h2>{#if findings.length===0}<p class="mt-2 text-sm">{$t("ui_fcb2dbb6c3d8")}</p>{/if}{#each findings as f}<div class="mt-3 border-t border-base-300 pt-3"><strong>{$findingText(f, 'title')} × {f.count}</strong><span class="ml-2 font-mono text-xs">{f.code}</span><p>{$findingText(f)}</p><p class="text-sm opacity-70">{$findingText(f, 'action')}</p><details class="mt-2 text-xs"><summary>{$t("technical.details")}</summary><p>{f.message}</p><p>{f.action}</p></details>{#if f.task_id}<a class="link" href={`#/autopilot?project=${encodeURIComponent(id)}`}>{$t("ui_0a92e7687ea3")}</a>{/if}{#if f.chapter}<a class="link ml-3" href={`#/versions?project=${encodeURIComponent(id)}&chapter=${f.chapter}`}>{$t("ui_3ebc6bced828", {p0: f.chapter})}</a>{/if}</div>{/each}</div>
 <div class="rounded-xl border border-base-300 p-4"><h2 class="text-lg font-semibold">{$t("ui_fad912a5d5bb")}</h2><p class="text-xs opacity-60">{$t("ui_bb8948fe25f4")}</p>{#each page.health ?? [] as h}<p class="mt-2 text-sm"><strong>{h.provider}</strong> {$t("ui_81664368a89a", {p0: (h.manually_paused ? $t("ui_384230448428") : $stateLabel(h.state)), p1: h.consecutive_failures, p2: $codeText(h.last_error)})}{#if h.cooldown_until}{$t("ui_670f9dcb105d", {p0: h.cooldown_until})}{/if}</p>{/each}</div>
 <details class="rounded-xl border border-base-300 p-4"><summary class="cursor-pointer font-semibold">{$t("ui_22a0d243adb2")}</summary>
 {#if draft}<form class="mt-4 space-y-4" on:submit|preventDefault={save}>
 <p class="text-sm">{$t("ui_56cdc74fabeb", {p0: draftRevision})}</p>
 <div class="grid gap-3 md:grid-cols-3">
 <label class="form-control"><span class="label-text">{$t("ui_9740d324d2c9")}</span><input class="input input-bordered" bind:value={draft.currency} maxlength="3" required /></label>
 <label class="form-control"><span class="label-text">{$t("ui_76d2a6471bf4")}</span><input class="input input-bordered" type="number" min="0" step="0.000001" bind:value={projectBudget} required /></label>
 <label class="form-control"><span class="label-text">{$t("ui_3f029232fa42")}</span><input class="input input-bordered" type="number" min="0" step="0.000001" bind:value={taskBudget} required /></label>
 <label class="form-control"><span class="label-text">{$t("ui_c9351a81c1d8")}</span><input class="input input-bordered" type="number" min="0" max="1000000" bind:value={draft.project_max_calls} required /></label>
 <label class="form-control"><span class="label-text">{$t("ui_cf97f7a1ff9e")}</span><input class="input input-bordered" type="number" min="0" max="1000000" bind:value={draft.task_max_calls} required /></label>
 <label class="form-control"><span class="label-text">{$t("ui_ce7ae4052032")}</span><input class="input input-bordered" type="number" min="128" max="65536" bind:value={draft.max_output_tokens} required /></label>
 <label class="form-control"><span class="label-text">{$t("ui_153299d9b362")}</span><input class="input input-bordered" type="number" min="256" max="1000000" bind:value={draft.max_input_estimate} required /></label>
 <label class="form-control"><span class="label-text">{$t("ui_e774d721d540")}</span><input class="input input-bordered" type="number" min="1" max="20" bind:value={draft.failure_threshold} required /></label>
 <label class="form-control"><span class="label-text">{$t("ui_c90ed7f53ce4")}</span><input class="input input-bordered" type="number" min="1" max="86400" bind:value={draft.cooldown_seconds} required /></label>
 </div>
 <label class="form-control"><span class="label-text">{$t("ui_25c29e8a4eb4")}</span><input class="input input-bordered" bind:value={paused}/></label>
 <label class="flex items-center gap-2"><input class="checkbox checkbox-sm" type="checkbox" bind:checked={draft.require_known_price}/>{$t("ui_e7f74b4af50b")}</label>
 <label class="flex items-center gap-2"><input class="checkbox checkbox-sm" type="checkbox" bind:checked={draft.block_unknown_cost}/>{$t("ui_eb769de37f86")}</label>
 <h3 class="font-semibold">{$t("ui_64049fc5c5cb")}</h3><p class="text-xs opacity-60">{$t("ui_9cf74715bc00")}</p>
 {#each draft.prices as price,i}<div class="grid gap-2 md:grid-cols-5"><input aria-label={$t("ui_5d86ff6d1752", {p0: i+1})} class="input input-bordered input-sm" bind:value={price.provider} placeholder={$t("ui_9fdabbc01532")} required/><input aria-label={$t("ui_9320aa99abee", {p0: i+1})} class="input input-bordered input-sm" bind:value={price.model} placeholder={$t("ui_0068987fbb29")} required/><input aria-label={$t("ui_f906ef85177b", {p0: i+1})} class="input input-bordered input-sm" type="number" min="0" max="1000000000" bind:value={price.input_micros_per_million} required/><input aria-label={$t("ui_a141598c1c3c", {p0: i+1})} class="input input-bordered input-sm" type="number" min="0" max="1000000000" bind:value={price.output_micros_per_million} required/><button class="btn btn-sm" type="button" on:click={()=>{if(draft)draft.prices=draft.prices.filter((_,n)=>n!==i);}}>{$t("ui_6135d4159e89")}</button></div>{/each}
 <button class="btn btn-sm" type="button" disabled={draft.prices.length>=100} on:click={()=>{if(draft)draft.prices=[...draft.prices,{provider:'',model:'',input_micros_per_million:0,output_micros_per_million:0}];}}>{$t("ui_db66761103c5")}</button>
 <div class="flex gap-3"><button class="btn btn-primary" disabled={busy}>{$t("ui_0a7dba2cfe9a")}</button><button type="button" class="btn btn-outline" on:click={resetPolicy}>{$t("ui_e0cc3f0a503e")}</button></div>
 </form>{/if}</details>
 <div><h2 class="text-lg font-semibold">{$t("ui_91bc36b7606b")}</h2><div class="overflow-x-auto"><table class="table table-sm"><thead><tr><th>{$t("ui_c47b54e84e79")}</th><th>{$t("ui_b8fbad59a027")}</th><th>{$t("ui_05c518eb94a0")}</th><th>{$t("ui_d5c99483ed8f")}</th><th>{$t("ui_edab3ba76417")}</th></tr></thead><tbody>{#each page.groups as g}<tr><td>{$stateLabel(g.agent)}</td><td>{g.provider} / {g.model}</td><td>{g.totals.calls}</td><td>{$text(money(g.totals.known_cost_micros,page.settings.policy.currency))}</td><td>{g.totals.unknown_cost}</td></tr>{/each}</tbody></table></div></div>
 <form class="flex flex-wrap gap-2" on:submit|preventDefault={()=>{offset=0;void load();}}><input aria-label={$t("ui_fe5090f5733e")} class="input input-bordered input-sm" bind:value={task} placeholder={$t("ui_5a50e7472a20")}/><input aria-label={$t("ui_dc89c3a931b0")} class="input input-bordered input-sm" type="number" min="0" max="1000" bind:value={chapter}/><button class="btn btn-sm">{$t("ui_a8d572d66f80")}</button></form>
 <div class="overflow-x-auto"><table class="table table-sm"><thead><tr><th>{$t("ui_8618fd472957")}</th><th>{$t("ui_f819dc58e432")}</th><th>{$t("ui_4404902a5148")}</th><th>{$t("ui_6320b4a8722a")}</th><th>{$t("ui_44202e88f09f")}</th><th>{$t("ui_7fe8603c084e")}</th><th>{$t("ui_e99a6717b691")}</th></tr></thead><tbody>{#each page.attempts as a}<tr><td>{a.started_at}<br/>{$t("ui_e0d368c1f289", {p0: a.chapter})}</td><td class="font-mono text-xs">{a.logical_id.slice(0,12)}<br/>{a.task_id}</td><td>{$stateLabel(a.agent)}:{$stateLabel(a.operation)}<br/>{a.provider}/{a.model}</td><td>{$stateLabel(a.state)}<br/>{$codeText(a.error_code??'')}</td><td>{(a.input_tokens ?? $t("ui_4d8c1c5b4283"))} → {(a.output_tokens ?? $t("ui_4d8c1c5b4283"))}</td><td><span>{$text(money(a.cost_micros,a.currency))}</span><br/><span>{$stateLabel(a.cost_source)}</span></td><td>{#if a.cost_micros===null}<button class="btn btn-xs" on:click={()=>{reconciliation=a.id;amount=0;confirmed=false;}}>{$t("ui_185a23056281")}</button>{/if}</td></tr>{/each}</tbody></table></div>
 <div class="flex gap-3"><button class="btn btn-sm" disabled={offset===0||loading} on:click={()=>{offset=Math.max(0,offset-50);void load();}}>{$t("ui_c9b9ae7a6144")}</button><span>{offset+1}–{Math.min(offset+50,page.total)} / {page.total}</span><button class="btn btn-sm" disabled={offset+50>=page.total||loading} on:click={()=>{offset+=50;void load();}}>{$t("ui_8a8542f69648")}</button></div>
 {#if reconciliation}<form class="rounded-xl border border-warning p-4 space-y-3" on:submit|preventDefault={reconcile}><h3 class="font-semibold">{$t("ui_034234e34cb8")}</h3><p class="text-sm">{$t("ui_5bbfe1425931")}</p><label class="form-control"><span class="label-text">{$t("ui_5bd45a05bdc9", {p0: page.settings.policy.currency})}</span><input class="input input-bordered" type="number" min="0" step="0.000001" bind:value={amount} required/></label><label class="flex gap-2"><input type="checkbox" class="checkbox" bind:checked={confirmed}/>{$t("ui_2b50841098f1")}</label><button class="btn btn-warning" disabled={!confirmed||busy}>{$t("ui_3c0bfd00a5af")}</button><button class="btn ml-2" type="button" on:click={()=>reconciliation=''}>{$t("ui_2cd0f3be8738")}</button></form>{/if}
 {/if}
</section>
