import type { Pair } from './system';
export type DiagnosticField = 'title' | 'message' | 'action';
// Stable backend codes select display-only guidance; original payloads stay intact.
const rows: [string, string, string, string, string, string, string][] = [
 ['PROJECT_BUDGET_EXCEEDED TASK_BUDGET_EXCEEDED','预计费用超过预算','Estimated cost exceeds the budget','下一次请求的预计费用超过预算，已保存内容不受影响。','The next request is estimated to exceed the budget. Saved content is unaffected.','核对调用记录，调整预算后显式继续任务。','Review recorded calls, adjust the budget, then explicitly resume the job.'],
 ['PROJECT_CALL_LIMIT TASK_CALL_LIMIT','请求次数达到上限','Attempt limit reached','已达到模型尝试次数上限。','The configured model attempt limit has been reached.','检查重试原因，再调整上限或停止任务。','Inspect retry causes before adjusting the limit or stopping the job.'],
 ['MODEL_PRICE_REQUIRED','缺少模型单价','Model price missing','当前模型没有对应单价，无法进行预算检查。','No price is configured for this model, so its budget cannot be checked.','填写服务商别名和精确模型名对应的价格。','Enter prices matching the provider alias and exact model ID.'],
 ['UNRESOLVED_MODEL_ATTEMPT COST_RECONCILIATION_REQUIRED','请求或费用待确认','Request or cost needs confirmation','存在未完成记录或未知费用，不会视为零费用继续调用。','Unfinished attempts or unknown costs remain. They are never assumed to be free.','先暂停任务并核对服务商记录，明确确认费用后继续。','Pause the job, check provider records and explicitly reconcile costs before continuing.'],
 ['PROVIDER_PAUSED PROVIDER_COOLDOWN','服务商暂停或冷却','Provider paused or cooling down','服务商已被手动暂停或近期连续失败。','The provider was manually paused or experienced consecutive failures.','检查配置，等待冷却或解除暂停；不会自动发起付费探测。','Check configuration, wait for cooldown or unpause explicitly. No automatic paid probe is made.'],
 ['INPUT_ESTIMATE_LIMIT','输入估算超过上限','Input estimate limit exceeded','本次请求的估算输入超过安全上限。','Estimated input for this request exceeds the safety limit.','检查上下文和资料规模，不要绕过必需信息检查。','Review context and resource size without bypassing required-information checks.'],
 ['OBSERVATION_STORAGE_FAILED','调用记录无法保存','Attempt records could not be saved','调用记录或预算状态无法可靠保存。','Attempt records or budget state could not be saved reliably.','检查磁盘和数据库，保留已有成果，不要删除历史后重试。','Check disk and database health. Preserve existing work; do not delete history to retry.'],
 ['REVIEW_REQUIRED','等待人工审阅','Review required','等待人工审阅当前候选稿。','The current candidate is awaiting human review.','打开自动创作详情，查看当前候选版本后明确批准。','Open automatic writing details, inspect the current candidate and approve explicitly.'],
 ['CHAPTER_CONTEXT_CHANGED CONTEXT_BASELINE_REQUIRED','规划依据已变化','Planning context changed','当前计划依赖的事实或资料版本已变化。','Facts or resource versions used by the current plan have changed.','在章节版本中检查、接受并定稿保留内容后继续，不要强制覆盖。','Inspect, accept and finalize the retained content in Chapter versions before continuing. Do not force an overwrite.'],
 ['PLANNING_CONTEXT_FAILED AUTHORING_CONTEXT_FAILED','上下文编译失败','Context compilation failed','规划所需上下文未能安全编译。','Required planning context could not be compiled safely.','核对必需事实、视角和上下文预算。','Check required facts, POV boundaries and the context budget.'],
 ['EXISTING_DRAFT_REQUIRES_REVIEW IMPORT_REQUIRES_REVIEW','已有候选稿待审阅','Existing candidate requires review','发现已有未接受的正文或导入候选。','Existing unaccepted text or import candidates were found.','恢复原任务，或在章节版本中明确审核和定稿。','Resume the original job or explicitly review and finalize in Chapter versions.'],
 ['QUALITY_HOLD CONTINUITY_REWRITE_EXHAUSTED REWRITE_BUDGET_EXHAUSTED','质量检查阻止继续','Quality checks block continuation','质量检查或重写上限阻止继续。','Quality checks or the rewrite limit prevent continuation.','检查一致性和评审，不得用费用设置绕过质量检查。','Inspect continuity and review results. Cost settings cannot bypass quality checks.'],
 ['UNKNOWN_COST','部分费用未知','Some costs are unknown','部分请求费用未知，已知费用小计不是完整账单。','Some request costs are unknown. The known subtotal is not the complete bill.','核对价格和用量，必要时进行明确对账。','Check prices and usage, and reconcile explicitly when necessary.'],
 ['INCOMPLETE_FINAL','定稿提交未完成','Final commit incomplete','存在尚未完整提交的定稿。','Some finalization operations are not fully committed.','恢复原定稿操作，不能仅凭当前定稿指针判断完成。','Resume the original finalization operation. The active-final pointer alone does not prove completion.'],
 ['DERIVED_STATE_PENDING','派生状态等待重建','Derived state rebuild pending','摘要或检索可能不是最新版本。','Summaries or retrieval data may be outdated.','通过版本恢复与重建流程处理，再继续写作。','Complete the version recovery/rebuild workflow before continuing to write.'],
 ['UNRESOLVED_TRUTH_CONFLICT','存在未解决事实冲突','Unresolved fact conflicts','事实库保留了未解决冲突。','The fact store retains unresolved conflicts.','核对来源和章节范围，通过显式事实修正处理。','Check provenance and chapter ranges, then apply explicit fact corrections.'],
 ['TOKEN_ESTIMATE_DRIFT','用量明显超过估算','Usage exceeds estimates','部分返回用量明显超过本地输入估算。','Some reported usage significantly exceeds the local input estimate.','检查服务商计费字段和上下文；当前费率只按输入与输出总量估算。','Check provider billing fields and context. Current rate estimates use total input and output only.'],
 ['TASK_PROGRESS_STALE','任务进度长时间未更新','Job progress has not updated','任务超过十分钟没有新持久化进度，这并不直接证明死锁。','No new persisted job progress for over ten minutes; this alone does not prove a deadlock.','先检查当前调用与控制意图，不要启动第二个写作进程。','Inspect the active call and requested controls. Do not start a second writing process.'],
 ['OVERDUE_FORESHADOWS','存在逾期伏笔','Overdue foreshadows','当前章节存在逾期伏笔。','There are overdue foreshadows at the current chapter.','在伏笔管理中查看来源和回收窗口；诊断不会自动回收。','Inspect provenance and payoff windows in Foreshadows. Diagnostics never resolve them automatically.']
];
export const diagnostics: Record<string, Record<DiagnosticField, Pair>> = {};
for (const [codes, zhTitle, enTitle, zhMessage, enMessage, zhAction, enAction] of rows) {
  for (const code of codes.split(' ')) diagnostics[code] = { title: [zhTitle, enTitle], message: [zhMessage, enMessage], action: [zhAction, enAction] };
}
