// Temporary release preparation. Removed together with migration helpers before merge.
import fs from 'node:fs';
import {createHash} from 'node:crypto';
const hash=s=>'ui_'+createHash('sha256').update(s).digest('hex').slice(0,12);
if(process.argv[2]!=='finalize'){
  const path='web/src/pages/Projects.svelte';let source=fs.readFileSync(path,'utf8');
  const old=`<h1 class="workspace-title">{$t("${hash('项目')}")}</h1>`;
  if(!source.includes(old))throw Error('Project heading source changed; review before replacing');
  fs.writeFileSync(path,source.replace(old,`<h1 class="workspace-title">{$t("${hash('Projects')}")}</h1>`));
  const browser='scripts/i18n-browser.mjs';let audit=fs.readFileSync(browser,'utf8');
  audit=audit.replace("}catch(error){writeFileSync", "}catch(error){console.error('BROWSER_LAST_VIEW', await evaluate(\"JSON.stringify({url:location.href,title:document.title,heading:document.querySelector('main h1')?.textContent,text:document.body.innerText.slice(0,2000)})\").catch(()=>''));writeFileSync");
  fs.writeFileSync(browser,audit);
  process.exit(0);
}
const report=JSON.parse(fs.readFileSync('verification-results/i18n/result.json','utf8'));
if(report.route_views!==28||report.model_attempts!==0||report.language_switch_api_writes!==0||report.browser_exceptions.length||report.http_5xx.length)throw Error('Incomplete browser acceptance evidence');
const run=process.env.GITHUB_RUN_ID;
let readme=fs.readFileSync('README.md','utf8').replaceAll('v0.1.0-rc.1','v0.1.0-rc.2');
readme=readme.replace('# NovelForge\n','# NovelForge\n\n[English](README.en.md) · [中英界面说明](docs/I18N.md)\n');
readme=readme.replace('## 当前状态','## 中英双语工作台\n\n顶部或“设置 → 界面语言”可切换 **简体中文 / English**，刷新后保留偏好。两种界面覆盖全部 14 个页面、操作提示、表单校验与诊断指导。切换不刷新页面，不更改作品的创作语言，不丢失未保存编辑或所选文件，不改变任务，也不触发模型请求。用户正文、资料、模型标识和原始技术记录保持原样。\n\n`v0.1.0-rc.2` 的变更与验收边界见 [候选版说明](docs/releases/v0.1.0-rc.2.md)。\n\n## 当前状态');
fs.writeFileSync('README.md',readme);
fs.mkdirSync('docs/releases',{recursive:true});
const notes=`# NovelForge v0.1.0-rc.2 — 中英双语工作台 / Bilingual workspace\n\n## 变化 / Changes\n\nAll 14 Web routes now offer complete Simplified Chinese and English controls, navigation, validation, task states and actionable diagnostics. Switch from the header or Settings; the browser remembers the choice. Manuscript language is independent, including existing Traditional Chinese projects.\n\n全部 14 个页面提供中英界面。切换只改变浏览器展示偏好，不刷新页面，不改作品、创作语言、未保存正文、光标、所选导入文件或预算编辑，不暂停、重启或恢复任务，也不触发模型调用。原始正文、资料、模型名称、API 数据和技术详情保持原样。\n\n## Evidence / 验证记录\n\nThe focused delivery check contains **18 bilingual tests + 23 existing affected page/wizard tests**, with zero Svelte/TypeScript errors or warnings. The AST guard checks App plus 14 routes for untranslated static operation text/attributes and explicit option values. A native embedded Go executable and real Chrome check **28 route/language views**, editable control identity/value preservation, persisted preference reload, unchanged original manuscript and project language, unchanged jobs, zero switch-induced API writes, zero model attempts, zero browser exceptions and zero HTTP 5xx.\n\nThe implementation audit is recorded in Actions **${run}**. Its materialized source is committed after success. The final PR repeats the read-only checks against the committed source; candidate publication independently runs the normal bounded quick gates and bilingual test guards against the merged commit. The release manifest identifies the exact packaged commit.\n\n## Upgrade / 升级\n\nBack up the workspace before replacing the executable. Keep the existing workspace and configuration directories. No project database schema or configuration migration is introduced by interface localization. Select the matching OS/architecture archive, verify the published SHA-256 checksums, then start \`novelforge server --workspace <workspace>\`. An existing rc.1 binary does not update itself when main changes.\n\n升级前备份工作区，再替换可执行文件；保留已有工作区和配置。此次国际化不引入项目数据库格式迁移。首次评估使用独立测试工作区，必要时添加 \`--no-autopilot\` 关闭任务执行器；该参数不是全局只读模式。\n\n## Limits / 边界\n\nThis is a prerelease, not stable/latest. The bilingual scope is Web, not a translation of CLI/TUI, prompts or manuscripts. Technical identifiers and raw diagnostic details intentionally retain their source values. Running-job invariance uses component tests; the live-browser audit runs without a paid provider. Full Phase 13B regression, long-book scale, paid-provider billing/literary quality and Windows/macOS/ARM native runtime acceptance remain unverified. Six packages are cross-built, with native Linux no-model smoke separately recorded. SHA-256 is not OS signing or notarization.\n`;
fs.writeFileSync('docs/releases/v0.1.0-rc.2.md',notes);
fs.appendFileSync('docs/I18N.md',`\n## Delivery evidence\n\nImplementation audit: GitHub Actions ${run}; 18 focused bilingual tests, 23 affected existing tests and 28 real route/language views. The final PR repeats checks on committed source. See [rc.2 notes](releases/v0.1.0-rc.2.md).\n`);
fs.writeFileSync('README.en.md',`# NovelForge\n\n[简体中文](README.md) · [Interface languages](docs/I18N.md) · [rc.2 notes](docs/releases/v0.1.0-rc.2.md)\n\nNovelForge is a local-first long-form fiction workspace built with Go, SQLite and an embedded Web interface. It combines structured story facts, chapter-bounded character knowledge, narrative ledgers, budgeted context, immutable chapter versions, resumable writing jobs, writing skills/reference libraries, import/export/backup and cost diagnostics. Model proposals do not become authoritative facts until the chapter is accepted and finalized.\n\n## Bilingual workspace\n\nChoose **简体中文 / English** in the header or Settings. Switching changes only the browser display preference. It preserves projects, manuscript language, unsaved edits, cursor/selection, selected files and tasks, and never invokes a model. Original manuscripts, resource Markdown and technical records are not translated.\n\n## Getting started\n\nDownload the matching \`v0.1.0-rc.2\` prerelease archive from GitHub Releases and verify \`novelforge_checksums.txt\`. Extract into a new directory, then start in a separate test workspace:\n\n\`\`\`sh\n./novelforge server --workspace ./workspace-test --no-autopilot\n\`\`\`\n\nOn Windows use \`.\\novelforge.exe\`. Open \`http://127.0.0.1:48090\`. The flag disables the automatic task worker, not all writes. Configure providers using server-side files/environment references; do not store credentials in the browser. Set explicit model prices and budgets before removing the flag and starting paid work. The local server is not a public multi-user authenticated service.\n\nCreate a novel and save its foundation request, or import existing text as reviewable candidates. Configure resources and model roles, start a bounded writing job explicitly, then inspect/check/accept/finalize candidates in Chapter versions. Export finalized text and make project ZIP backups regularly.\n\n## Source build\n\nUse the Go version in \`go.mod\` (1.25.5). The committed \`web/dist\` is embedded into the binary. Frontend changes require Node 22 and rebuilding the embedded assets.\n\n\`\`\`sh\nCGO_ENABLED=0 go build -trimpath -o novelforge ./cmd/novelforge\n./novelforge server --workspace ./workspace-test --no-autopilot\n\`\`\`\n\n## Verification boundaries\n\nPhase 1–12 capabilities and Phase 13A candidate delivery are implemented; Phase 13B full acceptance is pending. The rc.2 change has focused bilingual/state-preservation tests and real Chrome route checks, not full scale or paid-model literary certification. Linux native no-model smoke is recorded; other platform archives require native acceptance. This is a prerelease, not stable/latest.\n\nSee [deployment](docs/DEPLOYMENT.md), [local acceptance](docs/LOCAL_ACCEPTANCE.md), [architecture](docs/ARCHITECTURE.md) and [documentation index](docs/README.md). Retained upstream code and notices remain under their stated licenses.\n`);
let packaging=fs.readFileSync('scripts/package_candidate.py','utf8');packaging=packaging.replace("INCLUDED = ['README.md'", "INCLUDED = ['README.en.md','docs/I18N.md','docs/releases/v0.1.0-rc.2.md','README.md'");fs.writeFileSync('scripts/package_candidate.py',packaging);
let candidate=fs.readFileSync('.github/workflows/candidate.yml','utf8');
candidate=candidate.replace('      - name: Build six archives with exact source identity','      - name: Verify bilingual guards for the exact candidate source\n        run: |\n          npm run check:i18n --prefix web\n          npm run test:i18n --prefix web\n      - name: Build six archives with exact source identity');
candidate=candidate.replace("          Path('release-notes.md').write_text(notes)","          if tag == 'v0.1.0-rc.2':\n            notes = f'## 中英双语工作台 / Bilingual workspace\\n\\n全部 14 个 Web 页面支持简体中文与 English。顶栏或设置切换，保持作品、创作语言、未保存编辑、文件选择和任务状态，不触发模型调用。\\n\\nAll 14 Web routes support Chinese and English. Switching preserves manuscripts, unsaved edits, file selections and jobs; it never starts model calls. The change passed 18 bilingual tests, 23 affected page tests and 28 real browser route/language checks. See docs/I18N.md and docs/releases/v0.1.0-rc.2.md included in every archive.\\n\\n' + notes\n          Path('release-notes.md').write_text(notes)");
fs.writeFileSync('.github/workflows/candidate.yml',candidate);
fs.writeFileSync('.github/workflows/i18n.yml',`name: Bilingual workspace checks\non:\n  pull_request:\n  push:\n    branches: [main]\n  workflow_dispatch:\npermissions:\n  contents: read\nconcurrency:\n  group: bilingual-${{ github.ref }}\n  cancel-in-progress: true\njobs:\n  bilingual:\n    runs-on: ubuntu-latest\n    timeout-minutes: 20\n    steps:\n      - uses: actions/checkout@v4\n        with:\n          persist-credentials: false\n      - uses: actions/setup-node@v4\n        with:\n          node-version: '22'\n      - uses: actions/setup-go@v5\n        with:\n          go-version-file: go.mod\n      - run: npm ci --prefix web\n      - name: Dictionary, static text and affected interaction gates\n        run: |\n          npm run check:i18n --prefix web\n          npm run check --prefix web -- --fail-on-warnings\n          npm run test:i18n --prefix web\n          npm test --prefix web -- src/pages src/lib/wizard.test.ts\n      - name: Reproducible embedded production build\n        run: |\n          npm run build --prefix web\n          git diff --exit-code -- web/dist web/package-lock.json\n          CGO_ENABLED=0 go build -o /tmp/novelforge ./cmd/novelforge\n      - name: Real bilingual browser with an isolated project and no paid provider\n        run: |\n          sudo apt-get update -qq\n          sudo apt-get install -y fonts-noto-cjk >/dev/null\n          node scripts/i18n-browser.mjs /tmp/novelforge\n      - uses: actions/upload-artifact@v4\n        if: always()\n        with:\n          name: bilingual-browser-${{ github.sha }}\n          path: verification-results/i18n\n          if-no-files-found: warn\n`);
for(const path of ['web/localize.mjs','web/prepare-i18n.mjs','web/post-i18n.mjs','web/i18n-translations.tsv','web/review-i18n.py','web/review-system.json','.github/workflows/i18n-maintenance.yml','web/finish-i18n.mjs'])fs.unlinkSync(path);
console.log('Prepared clean rc.2 delivery; removed all self-writing/migration helpers.');
